#! /usr/bin/env bash

## This is a poor approach, string script manipulation.
## It would be better if we could just remote call methods. 
## Will need further investigation.

## Sync
to_helios


HELIOS_CODE='
    cd ~/COCO;

    ## Remove previous logged stdout/stderr. This likely should be an option
    ls | grep -E "^[[:digit:]]+\.(out|err)$" | xargs rm

    ## Print msub script, and run it
    cat LAUNCHER/monothread_launch.sh ;
    msub LAUNCHER/monothread_launch.sh ;

    ## Monitor stdout/stderr. Should probably an option
    while true ; do
        tput reset ;
        cat ./*.out ;
        sleep 2 ;

        tput reset ;
        cat ./*.err ;
        sleep 2 ;
    done ;
'
## Kill the other jerbs first
if [[ $1 == "q" ]] ; then
  echo "We will kill the other jobs."
  HELIOS_CODE="
  ## Get the five digit jobs numbers for our running jobs, 
  ## then iteratively stop them with xargs qdel.
  ### Todo : there must be a way to directly query only running 
  ### jobs, and a way to only query job numbers. This would constitute in a more solid approach.
  qstat -u julesgm |
    grep ' R ' |
    grep -oE '[0-9]{5}' |
    xargs -I {} qdel {};
  $HELIOS_CODE
  "
fi ;

echo "$HELIOS_CODE"
ssh helios "$HELIOS_CODE"
