#!/usr/bin/python
"""
get which modules to import
"""
from __future__ import print_function
#from six.moves import iteritems
import re, sys, os
from snakefood.filter import do_filter

# The libraries of the ignore_set have heavy reliance on native / external libraries,
# and need to be installed "by hand"
ignore_set = {"numpy",
              "tensorflow",
              }
# Modules that have different repo names from their module names. Probably surprisingly, not that common.
replace_dict = {"enum": "enum34"
                }

modules_to_add = set()

# to ignore doubles.. even if we ignored or replaced them
done_set = set()

for x in do_filter():
    (fbase, ffn), (tbase, tfn) = x
    if ((re.match('/usr/lib/python', fbase) or
         (tbase and re.match('/usr/lib/python', tbase))) and
        not (re.match('site-packages', fbase) or
             (tbase and re.match('site-packages', tbase)))):
            continue

    base_module = tfn.split("/")[0].lower()

    if base_module.endswith(".py"):
        base_module = base_module[:-3]

    # Ignore doubles
    if base_module in done_set:
        continue

    # Ignore those from the ignore set
    if base_module not in ignore_set:
        if base_module not in replace_dict:
            modules_to_add.add(base_module)
        else:
            modules_to_add.add(replace_dict[base_module])
            done_set.add(replace_dict[base_module]) # we also add the values we replaced it with to the done_set

    else:
        sys.stderr.write("\tWarning: {} is in the ignore_set.\n".format(base_module))

    done_set.add(base_module)

for k in modules_to_add:
    print("{}".format(k))
